### ISSUE TITLE
find compatible connector (female) for C132463

### ISSUE THREAD

**Issue by derikon** [TactileVision/TactJam-hardware#5]
The actuators on the dev-board are conntect via XH header [C132463](https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_Ckmtw-Shenzhen-Cankemeng-C132463_C132463.html). We need to find the compatible counter part (female).

## Proposed solution by Alexander

Perhaps we can use something like this:
- https://www.digikey.de/product-detail/de/jst-sales-america-inc/XHP-2/455-2266-ND/555485
- https://www.digikey.de/product-detail/de/molex/0351550200/WM3137-ND/2405551
- https://lcsc.com/product-detail/Rectangular-Connectors-Housings_JST-Sales-America_XHP-2_JST-Sales-America-XHP-2_C144401.html

**comment by @derikon**
As far as I can see from the images none of the proposed connectors seem to fit. In case we can change the female connectors if you can find any corresponding parts.

## Proposed alternative by Dennis

Alternatively, why not just use a 16pin-connector:

- https://lcsc.com/product-detail/New-Arrivals_JST-Sales-America-XHP-16_C495639.html
- https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_JST-Sales-America-S16B-XH-A-LF-SN_C157933.html

I am not 100% sure if they fit perfectly...

**Comment by M6QF** [comment]
I can install the proposed one, although I personally don't like large pin connectors.

Alternatively, we can use these connectors C160237 (JST-PH-2) with already preinstalled female connectors:
https://www.amazon.de/St%C3%BCck-Stecker-Schwarz-Silikon-Buchse/dp/B07449V33P 

For another version (not the release one!) I plan to use audio jacks (SMT) [1] instead of MOLEX-/JST-connectors.
[1] https://lcsc.com/product-detail/Audio-Video-Connectors_Korean-Hroparts-Elec-PJ-327C-4A_C145813.html

**Comment by derikon** [comment]
We need to find another supplier that can deliver as much parts as we need.
