### ISSUE TITLE
do we need a power switch on the PCB

### ISSUE THREAD

**Issue by derikon** [TactileVision/TactJam-hardware#6]
The dev-board has a power switch to en-/disable the second USB which is used as power supply.

**Comment by M6QF** [comment]
I'm going to remove the switch in the release version, since it doesn't add functionality.
Furthermore, I'm not satisfied with the current power configuration. The shift-registers somehow manage to
produce voltage through data transfer. I'm going to address this issue in the future, but due to the lack of time not for the upcoming release version.
